export enum ProductStatus {
  DRAFT = "DRAFT",
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  ARCHIVED = "ARCHIVED",
}

export enum UserRole {
  ADMIN = "ADMIN",
  SALES = "SALES",
  WAREHOUSE = "WAREHOUSE",
  CUSTOMER = "CUSTOMER",
}

export enum OrderStatus {
  PENDING_PAYMENT = "PENDING_PAYMENT",
  PENDING_CONFIRMATION = "PENDING_CONFIRMATION",
  PACKING = "PACKING",
  SHIPPING = "SHIPPING",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  DELIVERY_FAILED = "DELIVERY_FAILED",
  RETURN_REQUESTED = "RETURN_REQUESTED",
  RETURN_PROCESSING = "RETURN_PROCESSING",
  RETURN_COMPLETED = "RETURN_COMPLETED",
}

export enum ReturnType {
  EXCHANGE = "EXCHANGE",
  REFUND = "REFUND",
}

export enum ReturnRequestStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  SHIPPING_BACK = "SHIPPING_BACK",
  RECEIVED = "RECEIVED",
  COMPLETED = "COMPLETED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
}

export enum ItemReturnStatus {
  NONE = "NONE",
  HAS_REQUEST = "HAS_REQUEST",
  EXCHANGED = "EXCHANGED",
  REFUNDED = "REFUNDED",
  REJECTED = "REJECTED",
}

export type SystemLogAction =
  | "CREATE"
  | "UPDATE"
  | "DELETE"
  | "LOGIN"
  | "APPROVE"
  | "REJECT"
  | "PAYMENT"
  | "STOCK_CHANGE"
  | "STOCK_ADJUST";

export type PaymentStatus =
  | "PAID"
  | "UNPAID"
  | "PENDING"
  | "PENDING_REFUND"
  | "REFUNDED"
  | "PARTIAL_REFUNDED";
